(()=>{
'use strict';

const remoteStates=new Map(),remoteObjects=new Map(),disconnectTimers=new Map();
const remoteFireAt=new Map(),remoteMissileAt=new Map(),lastAcceptedHit=new Map();
const pingSent=new Map(),pingSamples=[];
const missileVisuals=[];
let ownId='',localSnap=null,localShieldUntil=0,countdownUntil=0,countdownStarted=0;
let pingNonce=0,lastPingNonceAt=0,netSeq=0,receivedPackets=0,lostPackets=0,lastStateAt=0;
let localMissileSeq=0,lastMissileTarget=null,lastLocalFireAt=0,lastLocalMissileAt=0;
let fps=60,fxLevel=2,lowFpsTicks=0,highFpsTicks=0,expanded=/[?&]netdiag=1\b/.test(location.search);
let stats={shots:0,hits:0,damage:0,bestStreak:0,streak:0,deaths:0,missiles:0,missileHits:0};
let patched=false,supabasePatched=false;

const oldPhone=/iP(hone|od)/.test(navigator.userAgent)&&Math.max(screen.width||0,screen.height||0)<=736;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Array.isArray(a)&&Array.isArray(b)?Math.hypot((a[0]||0)-(b[0]||0),(a[1]||0)-(b[1]||0),(a[2]||0)-(b[2]||0)):1e9;
const now=()=>Date.now();

const style=document.createElement('style');
style.textContent=`
#dwNetBadge{position:fixed;z-index:28;right:calc(8px + env(safe-area-inset-right));top:calc(8px + env(safe-area-inset-top));padding:7px 9px;border-radius:11px;border:1px solid #7fa69755;background:#0b1714e8;color:#dff7ec;font:800 9px/1.35 Consolas,monospace;letter-spacing:.03em;pointer-events:auto;cursor:pointer;user-select:none;min-width:88px;text-align:center;box-shadow:0 4px 18px #0006}#dwNetBadge.bad{border-color:#d86c5d88;color:#ffd0c7}#dwNetBadge.mid{border-color:#dab65f88;color:#ffe8aa}#dwNetBadge .more{display:none;margin-top:4px;padding-top:4px;border-top:1px solid #ffffff18;font-weight:600;color:#afc7ba;white-space:pre-line;text-align:left}#dwNetBadge.expanded .more{display:block}
#dwCountdown{position:fixed;inset:0;z-index:10050;display:none;place-items:center;background:#06100c66;pointer-events:auto;color:white;text-align:center;text-shadow:0 4px 20px #000}#dwCountdown.on{display:grid}#dwCountdown strong{display:block;font:900 clamp(72px,18vw,160px)/.9 system-ui}#dwCountdown span{font:800 12px Consolas;letter-spacing:.18em;color:#bfe7cf}
#dwSpawnShield{position:fixed;z-index:20;left:50%;bottom:calc(86px + env(safe-area-inset-bottom));transform:translateX(-50%);display:none;padding:7px 12px;border-radius:999px;border:1px solid #7cdfff88;background:#123542dd;color:#c9f3ff;font:800 10px Consolas;pointer-events:none}#dwSpawnShield.on{display:block}
#dwMissileCanvas{position:fixed;inset:0;z-index:10;pointer-events:none;width:100%;height:100%}
.dw-net-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:12px}.dw-net-stat{padding:10px;border-radius:11px;background:#ffffff08;border:1px solid #ffffff12}.dw-net-stat b{display:block;font-size:16px}.dw-net-stat small{font-size:9px;color:#aebeb6}
@media(max-width:700px){#dwNetBadge{font-size:8px;right:5px;top:5px;min-width:78px;padding:6px}.dw-net-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
`;
document.head.appendChild(style);

const badge=document.createElement('div');badge.id='dwNetBadge';badge.innerHTML='<div class="main">NET --</div><div class="more"></div>';badge.onclick=()=>{expanded=!expanded;badge.classList.toggle('expanded',expanded);};document.body.appendChild(badge);badge.classList.toggle('expanded',expanded);
const countdown=document.createElement('div');countdown.id='dwCountdown';countdown.innerHTML='<div><strong>3</strong><span>ONLINE MAÇ BAŞLIYOR</span></div>';document.body.appendChild(countdown);
const shieldHud=document.createElement('div');shieldHud.id='dwSpawnShield';document.body.appendChild(shieldHud);
const missileCanvas=document.createElement('canvas');missileCanvas.id='dwMissileCanvas';missileCanvas.setAttribute('aria-hidden','true');document.body.appendChild(missileCanvas);
const mctx=missileCanvas.getContext('2d',{alpha:true,desynchronized:true});
let mw=1,mh=1,mdpr=1;
function resizeMissile(){mw=Math.max(1,innerWidth);mh=Math.max(1,innerHeight);mdpr=Math.min(devicePixelRatio||1,oldPhone?1.05:fxLevel===0?1.15:1.55);missileCanvas.width=Math.round(mw*mdpr);missileCanvas.height=Math.round(mh*mdpr);missileCanvas.style.width=mw+'px';missileCanvas.style.height=mh+'px';mctx.setTransform(mdpr,0,0,mdpr,0,0);}resizeMissile();addEventListener('resize',resizeMissile,{passive:true});

function heading(yaw){return [-Math.sin(Number(yaw)||0),0,-Math.cos(Number(yaw)||0)];}
function add(a,b){return [a[0]+b[0],a[1]+b[1],a[2]+b[2]];}function sub(a,b){return [a[0]-b[0],a[1]-b[1],a[2]-b[2]];}function mul(a,s){return [a[0]*s,a[1]*s,a[2]*s];}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}function norm(a){const l=Math.hypot(a[0],a[1],a[2])||1;return [a[0]/l,a[1]/l,a[2]/l];}
function cameraFrame(){const s=localSnap;if(!s?.p)return null;const f=heading(s.yaw),cam=add(add(s.p,mul(f,-13)),[0,6,0]),target=add(add(s.p,mul(f,28)),[0,.7,0]),view=norm(sub(target,cam)),right=norm(cross(view,[0,1,0])),up=norm(cross(right,view));return {cam,view,right,up};}
function project(p,f){const v=sub(p,f.cam),z=dot(v,f.view);if(z<.6)return null;const aspect=mw/Math.max(1,mh),k=1/Math.tan(80*Math.PI/360),nx=dot(v,f.right)/z*k/aspect,ny=dot(v,f.up)/z*k;if(Math.abs(nx)>1.4||Math.abs(ny)>1.4)return null;return [(nx*.5+.5)*mw,(-ny*.5+.5)*mh,z];}
function spawnMissileVisual(id,targetId){const r=remoteStates.get(id);if(!r?.p)return;const target=targetId&&remoteStates.get(targetId)?.p?remoteStates.get(targetId).p:localSnap?.p;const dir=target?norm(sub(target,r.p)):heading(r.yaw);missileVisuals.push({id,targetId,p:[...r.p],dir,speed:34,born:performance.now(),trail:[]});if(missileVisuals.length>(oldPhone?6:12))missileVisuals.splice(0,missileVisuals.length-(oldPhone?6:12));playSpatial('missile',id);}
function renderMissiles(t){mctx.clearRect(0,0,mw,mh);const frame=cameraFrame();for(let i=missileVisuals.length-1;i>=0;i--){const m=missileVisuals[i],age=(t-m.born)/1000;if(age>2.25){missileVisuals.splice(i,1);continue;}const target=m.targetId&&remoteStates.get(m.targetId)?.p?remoteStates.get(m.targetId).p:localSnap?.p;if(target){const desired=norm(sub(target,m.p));m.dir=norm([m.dir[0]+(desired[0]-m.dir[0])*.055,m.dir[1]+(desired[1]-m.dir[1])*.055,m.dir[2]+(desired[2]-m.dir[2])*.055]);}m.speed=Math.min(88,m.speed+.85);m.p=add(m.p,mul(m.dir,m.speed/60));if((Math.floor(t/45)+i)%2===0)m.trail.push([...m.p]);const maxTrail=fxLevel===0?5:fxLevel===1?8:12;if(m.trail.length>maxTrail)m.trail.shift();if(!frame)continue;const head=project(m.p,frame);if(!head)continue;mctx.save();mctx.globalCompositeOperation='lighter';if(fxLevel>0){for(let j=0;j<m.trail.length;j++){const pp=project(m.trail[j],frame);if(!pp)continue;const a=(j+1)/m.trail.length*.32;mctx.fillStyle=`rgba(220,220,205,${a})`;mctx.beginPath();mctx.arc(pp[0],pp[1],fxLevel===2?3.2:2.2,0,Math.PI*2);mctx.fill();}}mctx.shadowColor='#ff9f45';mctx.shadowBlur=fxLevel===2?18:8;mctx.fillStyle='#fff1c6';mctx.beginPath();mctx.arc(head[0],head[1],oldPhone?3.8:5.2,0,Math.PI*2);mctx.fill();mctx.fillStyle='#ff7a32';mctx.beginPath();mctx.arc(head[0],head[1]+2,oldPhone?2.4:3.4,0,Math.PI*2);mctx.fill();mctx.restore();}requestAnimationFrame(renderMissiles);}requestAnimationFrame(renderMissiles);

let audioCtx=null;
function ensureAudio(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();}catch(_){}return audioCtx;}
document.addEventListener('pointerdown',ensureAudio,{passive:true});
function panFor(id){const r=remoteStates.get(id),l=localSnap;if(!r?.p||!l?.p)return 0;const to=norm(sub(r.p,l.p)),right=[Math.cos(Number(l.yaw)||0),0,-Math.sin(Number(l.yaw)||0)];return clamp(dot(to,right),-1,1);}
function playSpatial(kind,id){const a=ensureAudio();if(!a||a.state!=='running')return;const o=a.createOscillator(),g=a.createGain(),p=a.createStereoPanner?a.createStereoPanner():null,t=a.currentTime,pan=panFor(id);o.type=kind==='missile'?'sawtooth':'square';o.frequency.setValueAtTime(kind==='missile'?180:520,t);o.frequency.exponentialRampToValueAtTime(kind==='missile'?82:240,t+(kind==='missile'?.22:.045));g.gain.setValueAtTime(kind==='missile'?.025:.012,t);g.gain.exponentialRampToValueAtTime(.0001,t+(kind==='missile'?.28:.06));if(p){p.pan.value=pan;o.connect(g).connect(p).connect(a.destination);}else o.connect(g).connect(a.destination);o.start();o.stop(t+(kind==='missile'?.3:.07));}

function pingValue(){if(!pingSamples.length)return null;const a=[...pingSamples].sort((x,y)=>x-y);return Math.round(a[Math.floor(a.length*.5)]);}
function quality(){const p=pingValue(),loss=receivedPackets+lostPackets?lostPackets/(receivedPackets+lostPackets):0;if(!p)return 'BAĞLANIYOR';if(p<85&&loss<.03)return 'İYİ';if(p<165&&loss<.09)return 'ORTA';return 'ZAYIF';}
function updateBadge(){const p=pingValue(),loss=receivedPackets+lostPackets?Math.round(lostPackets/(receivedPackets+lostPackets)*100):0,age=lastStateAt?Math.round((performance.now()-lastStateAt)):0,q=quality();badge.classList.toggle('bad',q==='ZAYIF');badge.classList.toggle('mid',q==='ORTA');badge.querySelector('.main').textContent=`${q} · ${p??'--'} ms`;badge.querySelector('.more').textContent=`FPS ${Math.round(fps)} · Kayıp ~%${loss}\nState ${age} ms · FX ${['DÜŞÜK','ORTA','YÜKSEK'][fxLevel]}\nF8 / dokun: ağ testi`;const left=Math.max(0,localShieldUntil-now());if(left>0){shieldHud.classList.add('on');shieldHud.textContent=`SPAWN KORUMASI ${(left/1000).toFixed(1)} sn`;}else shieldHud.classList.remove('on');}setInterval(updateBadge,400);

let frameCount=0,lastFpsAt=performance.now();function fpsLoop(t){frameCount++;if(t-lastFpsAt>=1000){fps=frameCount*1000/(t-lastFpsAt);frameCount=0;lastFpsAt=t;if(fps<38){lowFpsTicks++;highFpsTicks=0;}else if(fps>53){highFpsTicks++;lowFpsTicks=0;}else{lowFpsTicks=Math.max(0,lowFpsTicks-1);highFpsTicks=Math.max(0,highFpsTicks-1);}if(lowFpsTicks>=2&&fxLevel>0){fxLevel--;lowFpsTicks=0;resizeMissile();}if(highFpsTicks>=5&&fxLevel<2&&!oldPhone){fxLevel++;highFpsTicks=0;resizeMissile();}}for(const [id,o] of remoteObjects){const st=remoteStates.get(id),shield=st&&Number(st.spawnProtectedUntil)>now();if(o?.__dwShield)o.__dwShield.visible=!!shield;}requestAnimationFrame(fpsLoop);}requestAnimationFrame(fpsLoop);

function ensureRemoteShield(result){if(!result?.mesh||result.__dwShield)return;const T=window.THREE;if(!T)return;try{const mat=new T.MeshBasicMaterial({color:0x63d9ff,transparent:true,opacity:.12,wireframe:true,depthWrite:false});const sh=new T.Mesh(new T.SphereGeometry(2.45,oldPhone?8:12,oldPhone?6:8),mat);result.mesh.add(sh);result.__dwShield=sh;}catch(_){}}
function isCountdown(){return performance.now()<countdownUntil;}
function showCountdown(){countdownStarted=performance.now();countdownUntil=countdownStarted+3300;countdown.classList.add('on');const tick=()=>{const left=countdownUntil-performance.now();if(left<=0){countdown.querySelector('strong').textContent='BAŞLA';countdown.querySelector('span').textContent='İYİ ŞANSLAR';setTimeout(()=>countdown.classList.remove('on'),420);return;}const n=Math.max(1,Math.ceil((left-250)/1000));countdown.querySelector('strong').textContent=String(n);requestAnimationFrame(tick);};tick();}
for(const ev of ['keydown','keyup','pointerdown','pointerup','touchstart','touchend'])window.addEventListener(ev,e=>{if(isCountdown()&&!e.target.closest?.('#dwOnline')){e.preventDefault();e.stopImmediatePropagation();}},{capture:true,passive:false});
addEventListener('keydown',e=>{if(e.code==='F8'){expanded=!expanded;badge.classList.toggle('expanded',expanded);}});

function appendResultStats(){const card=document.getElementById('dwCard');if(!card||card.querySelector('.dw-net-stats'))return;const h=card.querySelector('h2');if(!h||!/ZAFER|MAÇ TAMAMLANDI/.test(h.textContent))return;const accuracy=stats.shots?Math.round(stats.hits/stats.shots*100):0;const box=document.createElement('div');box.className='dw-net-stats';box.innerHTML=`<div class="dw-net-stat"><b>${stats.shots}</b><small>ATIŞ</small></div><div class="dw-net-stat"><b>${accuracy}%</b><small>İSABET</small></div><div class="dw-net-stat"><b>${Math.round(stats.damage)}</b><small>HASAR</small></div><div class="dw-net-stat"><b>${stats.bestStreak}</b><small>EN İYİ SERİ</small></div><div class="dw-net-stat"><b>${stats.deaths}</b><small>ÖLÜM</small></div><div class="dw-net-stat"><b>${pingValue()??'--'} ms</b><small>ORT. PING</small></div>`;const row=card.querySelector('.dw-row');if(row)card.insertBefore(box,row);else card.appendChild(box);}
new MutationObserver(appendResultStats).observe(document.documentElement,{subtree:true,childList:true});

function validateOutgoingHit(target,damage,weapon){if(isCountdown())return null;const t=remoteStates.get(target);if(!t)return null;if(Number(t.spawnProtectedUntil)>now())return null;if(localSnap?.team!=null&&t.team!=null&&localSnap.team===t.team&&window.DroneArenaOnlineBridge?.mode?.()==='2v2')return null;const range=weapon==='missile'?280:220;if(dist(localSnap?.p,t.p)>range)return null;const since=performance.now()-(weapon==='missile'?lastLocalMissileAt:lastLocalFireAt);if(since>(weapon==='missile'?6500:850))return null;const cap=weapon==='missile'?80:22;return clamp(Number(damage)||0,.1,cap);}
function stateFor(id){return id===ownId?localSnap:remoteStates.get(id);}
function validateIncomingHit(packet){if(!packet||!packet.source||!packet.target)return false;const a=stateFor(packet.source),b=stateFor(packet.target);if(!a?.p||!b?.p)return false;if(Number(b.spawnProtectedUntil)>now())return false;if(a.team!=null&&b.team!=null&&a.team===b.team&&window.DroneArenaOnlineBridge?.mode?.()==='2v2')return false;const weapon=packet.weapon==='missile'?'missile':'primary',range=weapon==='missile'?290:230;if(dist(a.p,b.p)>range)return false;const last=weapon==='missile'?remoteMissileAt.get(packet.source):remoteFireAt.get(packet.source);if(packet.source!==ownId&&(!last||performance.now()-last>(weapon==='missile'?7000:1100)))return false;const damage=Number(packet.damage)||0;if(damage<=0||damage>(weapon==='missile'?80:22))return false;const seq=Number(packet.shotSeq)||0,key=packet.source+'|'+weapon,lastSeq=lastAcceptedHit.get(key)||0;if(seq&&seq<=lastSeq)return false;const rateKey=key+'|'+packet.target,prev=lastAcceptedHit.get(rateKey)||0,stamp=performance.now();if(stamp-prev<(weapon==='missile'?280:28))return false;if(seq)lastAcceptedHit.set(key,seq);lastAcceptedHit.set(rateKey,stamp);return true;}

function patchSupabaseFactory(){if(supabasePatched||!window.supabase?.createClient)return false;const origCreate=window.supabase.createClient.bind(window.supabase);window.supabase.createClient=(...args)=>{const client=origCreate(...args),origChannel=client.channel.bind(client);client.channel=(...cargs)=>{const ch=origChannel(...cargs),origOn=ch.on.bind(ch),origSend=ch.send.bind(ch),origTrack=ch.track?.bind(ch);ch.on=(type,filter,cb)=>{if(type==='broadcast'&&filter?.event){const ev=filter.event;const wrapped=msg=>{const p=msg?.payload;if(ev==='fire'&&p?.id)remoteFireAt.set(p.id,performance.now());if(ev==='missile'&&p?.id)remoteMissileAt.set(p.id,performance.now());if(ev==='hit'&&!validateIncomingHit(p))return;return cb(msg);};return origOn(type,filter,wrapped);}return origOn(type,filter,cb);};ch.send=msg=>{if(msg?.type==='broadcast'&&msg.event==='hit'&&msg.payload){msg={...msg,payload:{...msg.payload,shotSeq:msg.payload.weapon==='missile'?localMissileSeq:netSeq,clientTs:now()}};}return origSend(msg);};if(origTrack)ch.track=(payload,...rest)=>{if(payload?.player_id)ownId=payload.player_id;return origTrack(payload,...rest);};return ch;};return client;};supabasePatched=true;return true;}
const originalAppend=Element.prototype.appendChild;Element.prototype.appendChild=function(node){if(node?.tagName==='SCRIPT'&&/supabase-js/.test(node.src||'')){const old=node.onload;node.onload=function(e){patchSupabaseFactory();return old?.call(this,e);};}return originalAppend.call(this,node);};patchSupabaseFactory();

function patchGame(){if(patched)return true;const bridge=window.DroneArenaOnlineBridge,net=window.DroneArenaOnlineNet;if(!bridge||!net||!bridge.snapshot||!bridge.upsertRemote)return false;const snap=bridge.snapshot.bind(bridge),upsert=bridge.upsertRemote.bind(bridge),remove=bridge.removeRemote?.bind(bridge),start=bridge.start?.bind(bridge),stop=bridge.stop?.bind(bridge),respawn=bridge.respawn?.bind(bridge),setLocalHP=bridge.setLocalHP?.bind(bridge),setRemoteHP=bridge.setRemoteHP?.bind(bridge),remoteFire=bridge.remoteFire?.bind(bridge),remoteMissile=bridge.remoteMissile?.bind(bridge);const localFire=net.onLocalFire?.bind(net),localMissile=net.onLocalMissile?.bind(net),localHit=net.onLocalHit?.bind(net);
  bridge.snapshot=()=>{const s=snap();if(!s)return s;localSnap={...s,p:Array.isArray(s.p)?[...s.p]:s.p,v:Array.isArray(s.v)?[...s.v]:s.v};const n=now();if(n-lastPingNonceAt>900){pingNonce=(pingNonce+1)>>>0;lastPingNonceAt=n;pingSent.set(pingNonce,n);for(const [k,t] of pingSent)if(n-t>6000)pingSent.delete(k);}const echoes=[];for(const r of remoteStates.values())if(r.pingNonce)echoes.push(r.pingNonce);s.netTs=n;s.netSeq=++netSeq;s.pingNonce=pingNonce;s.echoNonces=echoes.slice(-6);s.spawnProtectedUntil=localShieldUntil;s.missileSeq=localMissileSeq;s.missileTarget=lastMissileTarget;s.fxLevel=fxLevel;localSnap={...localSnap,...s};return s;};
  bridge.upsertRemote=(id,state)=>{if(!id)return upsert(id,state);const n=now(),prev=remoteStates.get(id)||{},seq=Number(state?.netSeq)||0,prevSeq=Number(prev.netSeq)||0;if(seq&&prevSeq&&seq>prevSeq+1)lostPackets+=seq-prevSeq-1;if(seq)receivedPackets++;lastStateAt=performance.now();if(Array.isArray(state?.echoNonces)){for(const nonce of state.echoNonces){const sent=pingSent.get(Number(nonce));if(sent){const rtt=n-sent;if(rtt>0&&rtt<3000){pingSamples.push(rtt);if(pingSamples.length>24)pingSamples.shift();}pingSent.delete(Number(nonce));}}}const delay=Math.max(0,Math.min(.18,(pingValue()||80)/2000+(n-Number(state?.netTs||n))/1000));const predicted={...state};if(Array.isArray(state?.p)&&Array.isArray(state?.v))predicted.p=[state.p[0]+state.v[0]*delay,state.p[1]+state.v[1]*delay,state.p[2]+state.v[2]*delay];remoteStates.set(id,{...prev,...state,__recv:n});const timer=disconnectTimers.get(id);if(timer){clearTimeout(timer);disconnectTimers.delete(id);}const result=upsert(id,predicted);if(result){remoteObjects.set(id,result);ensureRemoteShield(result);}const oldMissile=Number(prev.missileSeq)||0,newMissile=Number(state?.missileSeq)||0;if(newMissile&&oldMissile&&newMissile!==oldMissile)spawnMissileVisual(id,state?.missileTarget);return result;};
  if(remove)bridge.removeRemote=id=>{if(disconnectTimers.has(id))return;const timer=setTimeout(()=>{disconnectTimers.delete(id);remoteStates.delete(id);remoteObjects.delete(id);remove(id);},3500);disconnectTimers.set(id,timer);};
  if(respawn)bridge.respawn=(...args)=>{localShieldUntil=now()+2200;stats.streak=0;return respawn(...args);};
  if(setLocalHP)bridge.setLocalHP=(value,...rest)=>{const current=Number(localSnap?.hp);const next=Number(value);if(Number.isFinite(current)&&Number.isFinite(next)&&next<current&&now()<localShieldUntil)return;if(Number.isFinite(next)&&next<=0&&(!Number.isFinite(current)||current>0)){stats.deaths++;stats.streak=0;}return setLocalHP(value,...rest);};
  if(setRemoteHP)bridge.setRemoteHP=(id,value,...rest)=>{const r=remoteStates.get(id)||{},before=Number(r.hp);r.hp=Number(value);remoteStates.set(id,r);if(Number.isFinite(before)&&before>0&&Number(value)<=0&&performance.now()-(r.__lastHitByMe||0)<1800){stats.streak++;stats.bestStreak=Math.max(stats.bestStreak,stats.streak);}return setRemoteHP(id,value,...rest);};
  if(remoteFire)bridge.remoteFire=(id,...args)=>{remoteFireAt.set(id,performance.now());playSpatial('fire',id);return remoteFire(id,...args);};
  if(remoteMissile)bridge.remoteMissile=(id,...args)=>{remoteMissileAt.set(id,performance.now());playSpatial('missile',id);return remoteMissile(id,...args);};
  if(start)bridge.start=(...args)=>{stats={shots:0,hits:0,damage:0,bestStreak:0,streak:0,deaths:0,missiles:0,missileHits:0};remoteStates.clear();remoteObjects.clear();missileVisuals.length=0;receivedPackets=lostPackets=0;pingSamples.length=0;const out=start(...args);showCountdown();return out;};
  if(stop)bridge.stop=(...args)=>{for(const t of disconnectTimers.values())clearTimeout(t);disconnectTimers.clear();remoteStates.clear();remoteObjects.clear();missileVisuals.length=0;countdownUntil=0;countdown.classList.remove('on');return stop(...args);};
  if(localFire)net.onLocalFire=(...args)=>{if(isCountdown())return;lastLocalFireAt=performance.now();stats.shots++;return localFire(...args);};
  if(localMissile)net.onLocalMissile=(target,...rest)=>{if(isCountdown())return;lastLocalMissileAt=performance.now();localMissileSeq=(localMissileSeq+1)>>>0;lastMissileTarget=target||null;stats.missiles++;return localMissile(target,...rest);};
  if(localHit)net.onLocalHit=(target,damage,weapon,...rest)=>{const safe=validateOutgoingHit(target,damage,weapon);if(safe==null)return;stats.hits++;stats.damage+=safe;if(weapon==='missile')stats.missileHits++;const r=remoteStates.get(target);if(r)r.__lastHitByMe=performance.now();return localHit(target,safe,weapon,...rest);};
  patched=true;return true;}
if(!patchGame()){let tries=0;const timer=setInterval(()=>{tries++;if(patchGame()||tries>120)clearInterval(timer);},100);}
})();
